### ISSUE TITLE
npm run build failed on windows

### ISSUE THREAD

**Issue by anorudes** [chenglou/react-animation#10]
I desperately need help. Maybe I'm forgetting to do something 
Command "npm run build" failed on windows
![image](https://cloud.githubusercontent.com/assets/2178870/8512300/09c84484-2356-11e5-9387-f3e08cc39fbf.png)

**Comment by bsansouci** [comment]
Mmmh would it be because `NODE_ENV=production` doesn't work on Windows? Maybe it should be something like `set NODE_ENV=production`

**Comment by anorudes** [comment]
Thanks, I deleted a line in package.json and run "set NODE_ENV=production". It's working!
