### ISSUE TITLE
Define custom component tag name

### ISSUE THREAD

**Issue by arcthur** [chenglou/react-animation#20]
Hi,

I use the animation in react on different structure, not all of 'div', such as 'ul' or 'ol', so I want to the coder could be defined the component tag name.

**Comment by chenglou** [comment]
You don't have the restriction here. Use any tag you want:
```jsx
<Spring endValue={{val: 10}}>
  {interpolated => <ul>{interpolated.val}</ul>}
</Spring>
```

Hope that helps! =)
