### ISSUE TITLE
New name!

### ISSUE THREAD

**Issue by chenglou** [chenglou/react-animation#21]
React-animation is taken on npm. Let's find a better name for it.

Current suggestions:

- React-Spring (not sure, we might add `Decay` component later)
- React-Motion
- React-Move
- Reanimation
- React-Tween

**Comment by brentvatne** [comment]
`React-Motion` is nice

- React-Physics
- React-State-Physics
- React-Dynamic-Animation
- React-Pop :stuck_out_tongue:

**Comment by sebmck** [comment]
ng-react-animation-library-by-cheng-lou™.js

**Comment by chenglou** [comment]
@sebmck hmm good suggestion but I'm afraid it's hard to type `npm install ng-react-animation-library-by-cheng-lou™` in the terminal

**Comment by sebmck** [comment]
What about `npm install ⚛✨` then?

**Comment by chenglou** [comment]
Not sure how to require that from vim so I'll have to scratch that.

**Comment by devknoll** [comment]
I went from `react-animation` to `re-animation`. `reanimation` or `react-necromancer` :wink:

**Comment by andreypopp** [comment]
@chenglou did you try to contact react-animation package owner? It seems that package is abandoned and it is likely they can transfer package name to you.

**Comment by boopathi** [comment]
`react-motion` :+1: 

+ `react-anim`
+ `react-tween`
+ `react-transitions`

**Comment by chenglou** [comment]
@brentvatne react-pop would be neat, too bad this library has no association with Pop (except in spirit!)
@andreypopp: yeah I did, hasn't replied yet.
@devknoll re-animation...humm

**Comment by brentvatne** [comment]
I kind of like reanimation - brings linear, static animations to life :)

**Comment by dozoisch** [comment]
`re-animation` sound cool, but Im not sure people will associate it to react right away (so might be harder to find it)

**Comment by vramana** [comment]
How about `react-kinect` ??

**Comment by attilah** [comment]
react-motion :+1: 

what about, drumroll: react-animotion?

**Comment by dariocravero** [comment]
:+1: on re-animation or reanimation too :); ranimation could be another one too

**Comment by brentvatne** [comment]
I like kinetic too :smile:

**Comment by gaearon** [comment]
I like reanimation.

**Comment by attilah** [comment]
using the react- prefix make it WAY MORE easier to locate a package in the npm hell, so I'm against the "re" only prefix. Sorry @dariocravero  :D

**Comment by bobiblazeski** [comment]
spring-animation or reanimation

**Comment by dariocravero** [comment]
@attilah haha yeah, I know what you mean, we still have keywords though ;)

**Comment by chenglou** [comment]
Keyword should be fine enough to compensate for reanimation. I'm leaning toward that or react-motion

**Comment by dozoisch** [comment]
:+1: react-motion

**Comment by boopathi** [comment]
@chenglou 
while `react-motion` is pretty good, `react-animation` somehow sounds better. Try contacting npm.

**Comment by dmatteo** [comment]
`reanimation` is pretty cool!
How about `replay` or `react-play`?

**Comment by gaearon** [comment]
I like how `react-motion` is both pragmatic and hints that it's not your regular $.animate.

**Comment by bsansouci** [comment]
@gaearon I like the idea of avoiding the baggage of what $.animate entails :+1:

**Comment by nkbt** [comment]
React-motion sounds good.

**Comment by souporserious** [comment]
React-FX? I like React-Motion too :+1:

**Comment by DjebbZ** [comment]
`react-motion` : not tied to a specific technique/API (like Spring or Decay, and who knows what in the future) and still clear about the thematic. Also, prefixed by `react`.

**Comment by brentvatne** [comment]
react-motion seems popular so I registered that with a placeholder just in case some jerk tries to take it :P https://www.npmjs.com/package/react-motion - if you decide to go with that I will transfer it over for you

**Comment by paramaggarwal** [comment]
I vote for `reanimation`.

**Comment by chenglou** [comment]
<img width="568" alt="screenshot 2015-07-07 21 19 45" src="https://cloud.githubusercontent.com/assets/1909539/8562981/f19fcda2-24ed-11e5-8b07-dda9a9949df9.png">

Democracy has spoken! React-Motion it is. @brentvatne transfer please =)

Here are the honorable contenders:

- Reanimation (definitely the next animation library name)
- React-Tween
- React-⚛✨ (`import ⚛✨ from 'react-⚛✨`)

Thanks was fun, people! =)
Now back to polishing the library for the impending release. Closing!

**Comment by brentvatne** [comment]
@chenglou - transfer complete :smile: all yours

**Comment by mathieumg** [comment]
> React-⚛ (import ⚛✨ from 'react-⚛✨)

Unusable since you forgot a `'`! :trollface:  That being said, love the new name. :+1:
